version: "3"
services:
    www:
        build:
          context: ./apache-php
          args:
              - WITH_XDEBUG=false
        ports:
            - "8071:80"
        env_file: .env.docker
        # environment:
        #     XDEBUG_CONFIG: "remote_host=localhost remote_connect_back=1"
        #     PHP_IDE_CONFIG: "serverName=localhost"
        volumes:
            - ./:/var/www/html
        links:
            - db
        networks:
            - detector-network
    db:
        image: mysql
        restart: always
        ports:
            - "3374:3306"
        environment:
            MYSQL_DATABASE: detector
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./data:/var/lib/mysql
        networks:
            - detector-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8075:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        networks:
            - detector-network
    redis:
        image: redis:latest
        ports:
        - "6399:6379"
        volumes:
        - ./redis:/data
        networks:
            - detector-network

volumes:
    persistent:

networks:
    detector-network:
        driver: bridge
